[package]
name = "monexo-mint"
version = "0.1.0"
edition = "2021"

[lib]
name = "monexomint"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
async-trait = { workspace = true }
axum = { workspace = true, features = ["http2"] }
clap = { workspace = true, features = ["env", "derive"] }
chrono = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
monexo-core = { path = "../monexo-core", version = "0.2.1" }
utoipa = { workspace = true, features = ["axum_extras"] }
uuid = { workspace = true, features = ["serde", "v4"] }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls", "migrate", "macros", "uuid"] }
tokio = { workspace = true, features = ["full"] }
thiserror = { workspace = true }
solana-sdk = { workspace = true }
solana-client = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing-opentelemetry = { workspace = true }
